repositories:
  - lukasbach/scaffold-cli/templates/react
templates:
  react-fc:
    source: lukasbach/scaffold-cli/templates/react/react-fc
    defaults:
      importReactSymbols: true
  react-context:
    source: lukasbach/scaffold-cli/templates/react/react-context
    defaults:
      importReactSymbols: true
      deconstructProps: true
      propsType: type
