name: Publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v3
      - run: yarn
      - run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # # Automatically create binary executables:
  # TODO
  # publish-binary:
  #   runs-on: ubuntu-latest
  #   needs: prepare
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: volta-cli/action@v3
  #     - run: npx pkg . --out-dir ./exec/
  #     - uses: xresloader/upload-to-github-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         file: './exec/*'
  #         draft: false

